<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127152519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categoria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, imagen VARCHAR(500) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, puntuacion INT NOT NULL, usuario_id INT NOT NULL, categoria_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80B839D0DB38439E ON ranking (usuario_id)');
        $this->addSql('CREATE INDEX IDX_80B839D03397707A ON ranking (categoria_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D0DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D03397707A FOREIGN KEY (categoria_id) REFERENCES categoria (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D0DB38439E');
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D03397707A');
        $this->addSql('DROP TABLE categoria');
        $this->addSql('DROP TABLE ranking');
    }
}
