<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210164622 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranking_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tier VARCHAR(10) NOT NULL, ranking_id INT NOT NULL, moto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B626AA9420F64684 ON ranking_item (ranking_id)');
        $this->addSql('CREATE INDEX IDX_B626AA9478B8F2AC ON ranking_item (moto_id)');
        $this->addSql('ALTER TABLE ranking_item ADD CONSTRAINT FK_B626AA9420F64684 FOREIGN KEY (ranking_id) REFERENCES ranking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking_item ADD CONSTRAINT FK_B626AA9478B8F2AC FOREIGN KEY (moto_id) REFERENCES moto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking_valoracion DROP CONSTRAINT fk_3548b69a20f64684');
        $this->addSql('ALTER TABLE ranking_valoracion DROP CONSTRAINT fk_3548b69ad29aa1ac');
        $this->addSql('DROP TABLE ranking_valoracion');
        $this->addSql('ALTER TABLE ranking ADD fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE ranking DROP puntuacion');
        $this->addSql('ALTER TABLE ranking ALTER categoria_id SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranking_valoracion (ranking_id INT NOT NULL, valoracion_id INT NOT NULL, PRIMARY KEY (ranking_id, valoracion_id))');
        $this->addSql('CREATE INDEX idx_3548b69a20f64684 ON ranking_valoracion (ranking_id)');
        $this->addSql('CREATE INDEX idx_3548b69ad29aa1ac ON ranking_valoracion (valoracion_id)');
        $this->addSql('ALTER TABLE ranking_valoracion ADD CONSTRAINT fk_3548b69a20f64684 FOREIGN KEY (ranking_id) REFERENCES ranking (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ranking_valoracion ADD CONSTRAINT fk_3548b69ad29aa1ac FOREIGN KEY (valoracion_id) REFERENCES valoracion (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ranking_item DROP CONSTRAINT FK_B626AA9420F64684');
        $this->addSql('ALTER TABLE ranking_item DROP CONSTRAINT FK_B626AA9478B8F2AC');
        $this->addSql('DROP TABLE ranking_item');
        $this->addSql('ALTER TABLE ranking ADD puntuacion INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ranking DROP fecha');
        $this->addSql('ALTER TABLE ranking ALTER categoria_id DROP NOT NULL');
    }
}
