<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260121194917 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE moto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, marca VARCHAR(255) NOT NULL, modelo VARCHAR(255) NOT NULL, url_imagen VARCHAR(500) DEFAULT NULL, id_api VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre_usuario VARCHAR(255) NOT NULL, email VARCHAR(500) NOT NULL, password VARCHAR(500) NOT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE valoracion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estrellas INT NOT NULL, comentario TEXT DEFAULT NULL, usuario_id INT NOT NULL, moto_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D3DE0F4DB38439E ON valoracion (usuario_id)');
        $this->addSql('CREATE INDEX IDX_6D3DE0F478B8F2AC ON valoracion (moto_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE valoracion ADD CONSTRAINT FK_6D3DE0F4DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE valoracion ADD CONSTRAINT FK_6D3DE0F478B8F2AC FOREIGN KEY (moto_id) REFERENCES moto (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE valoracion DROP CONSTRAINT FK_6D3DE0F4DB38439E');
        $this->addSql('ALTER TABLE valoracion DROP CONSTRAINT FK_6D3DE0F478B8F2AC');
        $this->addSql('DROP TABLE moto');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE valoracion');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
